name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' 

    - name: Restore dependencies
      run: dotnet restore ./BudgetTracker.sln

    - name: Build the project
      run: dotnet build ./BudgetTracker.sln --no-restore --configuration Release 

    - name: Run tests
      run: dotnet test ./BudgetTracker.sln --no-restore --verbosity normal --configuration Release 

    - name: Collect Code Coverage
      run: dotnet test ./BudgetTracker.sln --collect:"XPlat Code Coverage"

    - name: Report Code Coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: '**/TestResults/**/*.xml'
